update kernel config

diff --git a/artifacts/kernel/build/pkg.yaml b/artifacts/kernel/build/pkg.yaml
--- a/artifacts/kernel/build/pkg.yaml
+++ b/artifacts/kernel/build/pkg.yaml
@@ -12,13 +12,13 @@ steps:
         cd /src
         cp -v /pkg/config .config
         cp -v /pkg/certs/* certs/
-      - |
-        cd /src
-        if [[ "${ARCH}" == "arm64" ]]; then
-            for patch in $(find /pkg/patches -type f -name "*.patch"); do
-              patch -p1 < $patch || (echo "Failed to apply patch $patch" && exit 1)
-            done
-        fi
+      #- |
+      #  cd /src
+      #  if [[ "${ARCH}" == "arm64" ]]; then
+      #      for patch in $(find /pkg/patches -type f -name "*.patch"); do
+      #        patch -p1 < $patch || (echo "Failed to apply patch $patch" && exit 1)
+      #      done
+      #  fi
     build:
       - |
         cd /src
